linters-settings:
  dupl:
    threshold: 100
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 65
    statements: 40
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
  gofumpt:
    extra-rules: true
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nestif:
    min-complexity: 4

linters:
  disable-all: true
  enable:
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - goerr113
    - gofumpt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nestif
    - nlreturn
    - paralleltest
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unparam
    - unused
    - wsl
    - whitespace

run:
  concurrency: 8
  timeout: 10m
  skip-dirs:
    - docs
    - bin
    - vendor
    - var
    - tmp
    - .cache
  skip-files:
    - \.pb\.go$
    - \.pb\.gw\.go$